// student-data.js
// Bible College of India - Student Data Storage

const STUDENT_DATA = {
    // Academic Performance Data
    marks: {
        'manoramaramane@gmail.com': { name: 'Manorama Ramane', marks: [90, 100, 97, 100, 100, 100, 93], offlineMark: 91 },
        'rvpardhe07@gmail.com': { name: 'Kavita Pardhe', marks: [92, 100, 100, 100, 100, 100, 86], offlineMark: 51 },
        'vypardh78@gmail.com': { name: 'Vishal Pardhe', marks: [89, 100, 100, 100, 100, 100, 74], offlineMark: 90 },
        'aadamgujare@gmail.com': { name: 'Aadam Gujare', marks: [93, 100, 100, 100, 100, 80, 88], offlineMark: 79 },
        'ranjeeta.kamble333@gmail.com': { name: 'Ranjana Kamble', marks: [52, 100, 100, 100, 100, 100, 94], offlineMark: 82 },
        'p82158860@gmail.com': { name: 'Pritee Gaikwad', marks: [63, 75, 90, 100, 100, 100, 76], offlineMark: 72 },
        'buddhiwantmeene@gmail.com': { name: 'Meena Buddhiwant', marks: [74, 70, 100, 100, 100, 100, 74], offlineMark: 88 },
        'khilarelajo@gmail.com': { name: 'Helen Khillare', marks: [74, 85, 100, 100, 100, 100, 69], offlineMark: 86 },
        'fkhilare@gmail.com': { name: 'Francis Khilare', marks: [77, 85, 70, 60, 80, 80, 90], offlineMark: 66 },
        'bhaleraojitesh727@gmail.com': { name: 'Jitesh Bhalerao', marks: [83, 50, 60, null, 90, 100, 72], offlineMark: 66 },
        'dpadvi604@gmail.com': { name: 'Dinesh Padvi', marks: [70, 100, 100, 50, 60, 60, null], offlineMark: 49 },
        'bordeamol26@gmail.com': { name: 'Amol Borde', marks: [90, 95, null, null, null, null, null], offlineMark: 71.5 },
        'borde.siyona@gmail.com': { name: 'Siyona Borde', marks: [93, 100, null, null, null, null, null], offlineMark: 83.5 },
        'manisha.fernandis15@gmail.com': { name: 'Manisha Fernandis', marks: [null, null, 70, 74, 50, null, 37], offlineMark: 60 },
        'meghadhusia09june@gmail.com': { name: 'Megha Mhaske', marks: [null, 48, 100, 40, null, null, null], offlineMark: null }, // 'N/A' in report
        'ashubaladon@gmail.com': { name: 'Ashish Dongerdive', marks: [75, 70, null, null, null, null, null], offlineMark: 84 },
        'vishforluv1982@gmail.com': { name: 'Vishwas Bhosale', marks: [62, 50, null, 100, 40, null, null], offlineMark: 43 },
        'brani4211@gmail.com': { name: 'Rani Bhosale', marks: [null, null, null, null, null, null, null], offlineMark: 46 },
        'michaelsalvi9324@gmail.com': { name: 'Michael Salvi', marks: [93, 70, 100, 74, 100, 100, 83], offlineMark: 47 } // Added Michael Salvi's marks entry
    },

    // Student Profile Information
    profiles: {
        'p82158860@gmail.com': {
            name: 'Pritee B. Gaikwad',
            address: 'Near Rahat Hospital, Dr Hibane building, Udgir 413517, MH',
            mobile: '9545366748',
            dob: '3/24/1965',
            age: 58,
            gender: 'Female',
            education: 'Graduate',
            occupation: 'Business',
            marital: 'Married',
            church: 'Methodist Church Udgir',
            pastor: 'Pastor Name Not Specified',
            reference1: 'Shobha Kamble - 8605592093',
            reference2: '',
            futurePlan: 'Preaching'
        },
        'ranjeeta.kamble333@gmail.com': {
            name: 'Ranjana Sangam Kamble',
            address: 'Andheri, Mumbai',
            mobile: '7506914392',
            dob: '5/22/1985',
            age: 40,
            gender: 'Female',
            education: '10th',
            occupation: 'Ministry',
            marital: 'Married',
            church: 'Jesus is Life Church',
            pastor: 'PS. Suraj Premani',
            reference1: 'Priti Gaikwad - 9545366748',
            reference2: '',
            futurePlan: 'Glorifying God\'s Name, Preaching Kingdom of God'
        },
        'manisha.fernandis15@gmail.com':{
            name: 'Manisha Fernandis',
            address: 'Mumbai, Ambernath',
            gender:'Female',
        },
        'vypardh78@gmail.com': {
            name: 'Vishal Yeshwant Pardhe',
            address: 'Global Residency, Tulip 304, Adivali, Namaskar Dhaba, Kalyan East 421306',
            mobile: '8655361379',
            dob: '10/3/1978',
            age: 47,
            gender: 'Male',
            education: '10th',
            occupation: 'Service',
            marital: 'Married',
            church: 'Holy Redeemer Church',
            pastor: 'Pastor Name Not Specified',
            reference1: 'Hendry Appa Pardhe - 8879474729',
            reference2: 'Damyanti Hendry Pardhe - 9222070542',
            futurePlan: 'To serve Lord with purity and honesty'
        },
        'rvpardhe07@gmail.com': {
            name: 'Kavita Vishal Pardhe',
            address: 'Global Residency, Tulip 304, Adivali, Namaskar Dhaba, Kalyan East 421306',
            mobile: '9029877366',
            dob: '12/17/1983',
            age: 40,
            gender: 'Female',
            education: '10th',
            occupation: 'Service',
            marital: 'Married',
            church: 'Holy Redeemer Church',
            pastor: 'Pastor Name Not Specified',
            reference1: 'Hendry Appa Pardhe - 8879474729',
            reference2: 'Damayanti Hendry Pardhe - 9222070542',
            futurePlan: 'To serve Lord with my family'
        },
        'manoramaramane@gmail.com': {
            name: 'Manorama Ashwin Ramane',
            address: '934 Shukrawar Peth, Baraimam Masjid, Pune 411001',
            mobile: '8208375825',
            dob: '12/3/1978',
            age: 45,
            gender: 'Female',
            education: '12th',
            occupation: 'Service',
            marital: 'Married',
            church: 'Pavitra Nam Devalay',
            pastor: 'Prist Karub',
            reference1: 'Mrs Anita Pawar - 9960377393',
            reference2: 'Mr Nishikant Pawar - 9890377393',
            futurePlan: 'Sandesh Dene'
        },
        'buddhiwantmeene@gmail.com': {
            name: 'Meena Hemant Buddhiwant',
            address: 'Bramha Emerald County A/2 Flat 604, NIBM Road, Kondhwa, Pune 411048',
            mobile: '9923334040',
            dob: '10/10/1973',
            age: 52,
            gender: 'Female',
            education: '12th',
            occupation: 'Business',
            marital: 'Married',
            church: 'Alliance Church',
            pastor: 'Rev Makasare',
            reference1: 'Anita Bhaldar - 9011924242',
            reference2: 'Rachel Koli - 7767930006',
            futurePlan: 'लोकांना खऱ्या देवाची ओळख करून देणे'
        },
        'vishforluv1982@gmail.com': {
            name: 'Vishwas Joseph Bhosale',
            address: 'Pimple Gurav, Sudarshan Nagar, Lane No 5, Maa Manzil, Pune 411061',
            mobile: '8788879755',
            dob: '8/19/1982',
            age: 42,
            gender: 'Male',
            education: '12th',
            occupation: 'Service',
            marital: 'Married',
            church: 'The Pentecostal Mission',
            pastor: 'Pastor George',
            reference1: 'Manisha Bhosale - 8698398734',
            reference2: 'Usha Bhosale - 7030178369',
            futurePlan: 'सेवेक'
        },
        'ashubaladon@gmail.com': {
            name: 'Ashish Chandrakant Dongardive',
            address: '302, D2, Krishna Estate, Dubey Baug Road, Hendrepada, Badlapur (W), Dist Thane 421503',
            mobile: '8975399863',
            dob: '12/17/1974',
            age: 50,
            gender: 'Male',
            education: 'Masters',
            occupation: 'Ministry',
            marital: 'Married',
            church: 'Jasiele Prayer Fellowship',
            pastor: 'Ashish Chandrakant Dongardive',
            reference1: 'Reference 1 - 9359168368',
            reference2: 'Reference 2 - 9763180289',
            futurePlan: 'लोकांना देवाच्या शिक्षणात ठेवणे, वाढवणे'
        },
        'bordeamol26@gmail.com': {
            name: 'Amol Borde',
            address: 'B202, Kute Fortune, Sainagar, Mamurdi, PCMC',
            mobile: '8805008272',
            dob: '3/26/1979',
            age: 46,
            gender: 'Male',
            education: 'Graduate',
            occupation: 'Business',
            marital: 'Married',
            church: 'Jesus Loves India Church Foundation',
            pastor: 'Pastor Sadanand Amolik',
            reference1: 'Samuel Amolik - 9604433770',
            reference2: '',
            futurePlan: 'Serving God'
        },
        'borde.siyona@gmail.com': {
            name: 'Siyona Borde',
            address: 'Mamurdi',
            mobile: '8805008273',
            dob: '9/1/1980',
            age: 45,
            gender: 'Female',
            education: 'Graduate',
            occupation: 'Business',
            marital: 'Married',
            church: 'Jesus Loves India Church Foundation',
            pastor: 'Pastor Sadanand Amolik',
            reference1: 'Amol Borde - 8805008272',
            reference2: 'Samuel Amolik - 9604433770',
            futurePlan: 'Winning Souls for God\'s Kingdom, Church planting'
        },
        'dpadvi604@gmail.com': {
            name: 'Dinesh Vanya Padvi',
            address: 'At Jugani, Po Jugani, Tel Dhadgaon, Dist Nandurbar',
            mobile: '7385535480',
            dob: '2/13/2002',
            age: 23,
            gender: 'Male',
            education: '10th',
            occupation: 'Service',
            marital: 'Married',
            church: 'Church Name Not Specified',
            pastor: 'Ruma Valvi',
            reference1: 'Ganesh Vanya Padvi - 8080107056',
            reference2: 'Vikram Vanya Padvi - 9420460782',
            futurePlan: 'देवाची सेवा करणे'
        },
        'brani4211@gmail.com': {
            name: 'Rani Vishwas Bhosale',
            address: 'Pimple Gaurav, Sudarshan Nagar Lane No 5, Near Sushti Chowk, Pune - 411061',
            mobile: '7499849874',
            dob: '8/15/1988',
            age: 36,
            gender: 'Female',
            education: '12th',
            occupation: 'Service',
            marital: 'Married',
            church: 'The Pentecostal Church',
            pastor: 'Pastor Name Not Specified',
            reference1: 'Vishwas Bhosale - 8788879755',
            reference2: 'Ranjana Banasode - 8850047608',
            futurePlan: 'To become God\'s servant'
        },
        'khilarelajo@gmail.com': {
            name: 'Helen Francis Khilare',
            address: 'B2, Flat No. 403, St. Luke Society, 1 Guruwar Peth, Pune - 411042',
            mobile: '9325506420',
            dob: '4/25/1969',
            age: 56,
            gender: 'Female',
            education: '10th',
            occupation: 'None',
            marital: 'Married',
            church: 'Church of the Holy Name',
            pastor: 'Pastor Ashok Karep',
            reference1: 'Rekha Salvi - 9604418628',
            reference2: 'Rajani Gaikwad - 9975375202',
            futurePlan: 'To preach the gospel and let people know about the only true living God Lord Jesus'
        },
        'fkhilare@gmail.com': {
            name: 'Francis Manuel Khilare',
            address: 'B2, Flat No 403, St Luke Society, 1 Guruwar Peth, Pune 42',
            mobile: '9325985914',
            dob: '12/10/1964',
            age: 60,
            gender: 'Male',
            education: '10th',
            occupation: 'None',
            marital: 'Married',
            church: 'Church of the Holy Name',
            pastor: 'Pastor Ashok Karep',
            reference1: 'Sandeep Bhore - 9881429922',
            reference2: 'Sanjay Barfe - 8468081159',
            futurePlan: 'To Preach the Gospel'
        },
        'bhaleraojitesh727@gmail.com': {
            name: 'Jitesh Rajendra Bhalerao',
            address: '180 Ghorpade Peth, Shankarsheth Road, Pune',
            mobile: '8983333727',
            dob: '5/15/1990',
            age: 34,
            gender: 'Male',
            education: 'Graduate',
            occupation: 'Service',
            marital: 'Married',
            church: 'Jesus Loves India Church Foundation',
            pastor: 'Pastor Name Not Specified',
            reference1: 'Durga Bhalerao - 8788738055',
            reference2: '',
            futurePlan: 'Gospel'
        },
        'meghadhusia09june@gmail.com': {
            name: 'Megha Shantilal Dhusia',
            address: 'A7 Ganesh Puram, Opp VWC, Pune Dapodi 12',
            mobile: '9028091883',
            dob: '6/9/1989',
            age: 35,
            gender: 'Female',
            education: 'Masters',
            occupation: 'Service',
            marital: 'Married',
            church: 'Emanuel AG Church',
            pastor: 'Pastor Name Not Specified',
            reference1: 'Akash Mhaske - 8796726320',
            reference2: 'Nikita Hiwale - 7745811984',
            futurePlan: 'Know the plan of God in my life, Have a daily relationship with Jesus, walk with Him'
        },
        'michaelsalvi9324@gmail.comm': {
            name: 'Michael Salvi',
            address: 'Jeevan Sinhha Co-op Housing Society, Ramne Sitaram Chawl, Parvati Paytha East, Pune-9, Behind Bharat Petrol Pump, 4th Floor',
            mobile: '9730524015',
            dob: '1982',
            age: 60,
            gender: 'Male',
            education: '12th',
            occupation: 'Not Specified',
            marital: 'Married',
            church: 'Believers Church',
            pastor: 'Pastor KCD Jacob',
            reference1: 'Pastor KCD Jacob',
            reference2: '',
            futurePlan: 'To serve the Lord to work, I want to tell the Gospel to the people to the other'
        },
        'aadamgujare@gmail.com': {
            name: 'Aadam Gujare',
            address: 'Near Marathi School, Kolhapur Haroli',
            mobile: '9022335090',
            gender: 'male',
            marital: 'Married'
        },
        'jlibiblecollege@gmail.com': {
            name: 'Bible College Admin',
            address: 'Bible College of India',
            mobile: 'N/A',
            dob: 'N/A',
            age: 'N/A',
            gender: 'N/A',
            education: 'N/A',
            occupation: 'Administrator',
            marital: 'N/A',
            church: 'Jesus Loves India Church Foundation',
            pastor: 'N/A',
            reference1: 'N/A',
            reference2: 'N/A',
            futurePlan: 'Administering Bible College'
        }
    },

    // Exam months mapping (updated to include offline)
    examMonths: ['June Exam', 'July Exam', 'August Exam', 'September Exam', 'October Exam', 'November Exam - 1 ', 'November Exam - 2', 'Offline Old testment Exam']
};
